### ISSUE TITLE
Login Sessions is expiring too early.

### ISSUE THREAD

**Issue by mrabro** [noelzappy/chatgpt-whatsapp#1]

**Comment by noelzappy** [comment]
Do you mean the login session of WhatsApp or that of ChatGPT?

If you mean WhatsApp, I have fixed that by using the `LocalAuth()` session persistence and this should persist the session longer.

**Comment by mrabro** [comment]
GPT session, in few minutes session is expiring, I have to re login.

**Comment by mrabro** [comment]
@noelzappy

**Comment by noelzappy** [comment]
> GPT session, in few minutes session is expiring, I have to re login.

Please can you confirm this still happens in the current implementation?
The login in is handled automatically by the `chatGPTBrowser` hence manual login is not required from your end. So long as you have the `password` and `email` in the `.env` file, it should auto-login whenever the session expires.

Also how long do you mean by "few minutes" @mrabro ?

**Comment by mrabro** [comment]
I added the credentials to `.env` file but still after few minutes, in my terminal shows session ended,

**Comment by noelzappy** [comment]
> I added the credentials to `.env` file but still after few minutes, in my terminal shows session ended,

Ok. Currently, ChatGPT says **"We're experiencing exceptionally high demand. Please hang tight as we work on scaling our systems."**, so let's wait till they have scaled for us to try again.
