### ISSUE TITLE
Whatsapp group

### ISSUE THREAD

**Issue by Cyberkingcr7** [noelzappy/chatgpt-whatsapp#4]
Could you make a group so that we could see the bot instead of running it

**Comment by noelzappy** [comment]
Hi @Cyberkingcr7, to test the bot, please join the [WhatsApp Group here](https://chat.whatsapp.com/G4OGbD2nA7bEgeggZO02jT)

Note, you'd have to use the prefixes in order to get a response.

**Comment by Cyberkingcr7** [comment]
Thanks bro... In addition to this are you able to join the group?
